### ISSUE TITLE
Add new scopes to the example client as a migration

### ISSUE THREAD

**Issue by dacrome** [osiam/auth-server#21]
Because two new scopes (ME, ADMIN) were added, we need to provide a flyway migration script to add them to the example client which will be created by default in the first version flyway migration script. I think we should only add the missing ME and ADMIN scope to the example-client, if it exists and not renamed or removed by the operator. If the client isn't existing anymore, the migration will be ignored. right?

**Comment by tkrille** [comment]
yeah, sounds viable. hard part will be determining if the client is still there and has not been changed so much ...

**Comment by dacrome** [comment]
Thanks to @tkrille, this is done with the option to create [flyway migrations in Java](https://github.com/osiam/auth-server/tree/master/src/main/java/db/migration).
