### ISSUE TITLE
Switch from xml to java configuration

### ISSUE THREAD

**Issue by dacrome** [osiam/auth-server#23]
The xml configuration should be removed and migrate to java configuration. The Spring Framework provides java configuration since version 3.1 and this can be done as a first step to [Spring Boot](http://projects.spring.io/spring-boot/). We already made good experience with the configuration migration in the [self-administration](https://github.com/osiam/addon-self-administration/pull/118). We should check if this step can be used to migrate [Spring OAuth2 version 1.0.5.RELEASE](https://github.com/osiam/auth-server/blob/master/pom.xml#L103) to the latest version 2.0.7.RELEASE to take advantage of the new configuration annotations. Maybe also a bump of the [Spring Security version](https://github.com/osiam/resource-server/blob/master/pom.xml#L80) to the latest 4.0.1.RELEASE is possible.

**Comment by dacrome** [comment]
We should think about to [import](http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-configuration-classes.html) most of the complicated spring oauth and security xml configuration files instead of migrate to java config. This step is a pre-step for the switch to Spring Boot, so this will be done sooner. After the switch to Spring Boot the java configuration should be migrate step-by-step and of course improve it by a newer version of the Spring OAuth and/or Security library and in general if possible.

**Comment by tkrille** [comment]
This is because the migration to `spring-security-oauth:2.x` is somewhat harder than usual, isn't it?

**Comment by dacrome** [comment]
I already migrate to Spring Boot, but with the mentioned import of the xml configuration. Just checkout [this branch](https://github.com/dacrome/auth-server/tree/spring-boot-xml-config). But some integration-test fail. Maybe someone has an idea what is wrong.

**Comment by dacrome** [comment]
Done with #50
