### ISSUE TITLE
Implement OTP for Two Factor Authentication

### ISSUE THREAD

**Issue by wallner** [osiam/auth-server#41]
Provide the ability to use two factor authentication with OSIAM. It would be a good feature to provide an implementation of OTP as specified in [RFC 6238](https://tools.ietf.org/html/rfc6238). For a start it might to be a good idea to take a look at [GoogleAuth](https://github.com/wstrange/GoogleAuth) and see how far we can get with that.

**Comment by tkrille** [comment]
Is there a `spring-security-...` component for that?

**Comment by thomasdarimont** [comment]
Hi, there are several impls / examples but nothing official AFAIK.
- [spring-security-otp](https://github.com/upcrob/spring-security-otp) 
- [grails-spring-security-otp](https://github.com/osoco/grails-spring-security-otp)
- [spring-security-otp-sample](https://github.com/osoco/spring-security-otp-sample)
- [two-factor-authentication-with-spring](http://altfatterz.blogspot.de/2014/02/two-factor-authentication-with-spring.html)
- [authentication-using-one-time-password-otp-technique-part-1](http://vitalflux.com/authentication-using-one-time-password-otp-technique-part-1/)
- [spring-security-otp-plugin-for-grails](https://prezi.com/mbqtxenlpsio/spring-security-otp-plugin-for-grails/)

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/78
