### ISSUE TITLE
Grant type password response json invalid?

### ISSUE THREAD

**Issue by ohoho7** [osiam/auth-server#42]
Hi, according to this site:
https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified#other-app-types
password grant type, should take only:
username, password, client_id
In your application, passing only those params causing credential error, I do not know where is mistake but I think that passing client-secret is necessary to avoid impersonate client by users...
So, I passed client-secret too and found out that response is:
{"access_token":"71eefd80-2af8-4864-8884-81ff73abd68d","token_type":"bearer","refresh_token":"cb13483b-5fa5-4092-a9a2-1dd4e1a6ca90","expires_in":25594,"scope":"POST PATCH GET DELETE PUT","user_name":"admin","scopes":"POST PATCH GET DELETE PUT ","refresh_token_expires_at":1438343827492,"expires_at":1438286227494,"user_id":"cef9452e-00a9-4cec-a086-d171374ffbef","token_type":"bearer","client_id":"example-client","refresh_token":"cb13483b-5fa5-4092-a9a2-1dd4e1a6ca90","access_token":"71eefd80-2af8-4864-8884-81ff73abd68d"}

Why there are two fields access_token and two fields refresh_token?
Is there some mistake in my configuration or it has to be in that way?

**Comment by wallner** [comment]
Hello @ohoho7,

you are absolutely right. We are using HTTP basic auth to authenticate the clients and prevent impersonation. We could make that configurable, but I'm not really sure that this is a good idea. Why would you need that?

Regarding the double keys in the response: You did nothing wrong, we consider it a bug on OSIAMs side and even though the JSON standard does neither allow or disallow double keys it is certainly not very pretty. I'm in the process of preparing a pull request that should fix this.

Thank you for spotting it!

**Comment by ohoho7** [comment]
Thanks for reply, in my case i can pass client secret but have a look on this quotation from pointed web site:
"The client secret must be kept confidential. If a deployed app cannot keep the secret confidential, such as Javascript or native apps, then the secret is not used."

To not create next topic I want to ask here, where I should search for mechanism which is filtering request by scopes? (sending GET to resource by client whithout assigment GET scope  will cause Access Denied but it is not sent from controller request mapping it is done earlier but where? )

**Comment by wallner** [comment]
Hello @ohoho7,

With passing the client password (or secret) the HTTP Basic authentication scheme we are implementing [section 2.3.1](https://tools.ietf.org/html/rfc6749#section-2.3.1) of the [OAuth2 RFC](https://tools.ietf.org/html/rfc6749):

> Clients in possession of a client password MAY use the HTTP Basic authentication scheme as
> defined in [RFC2617] to authenticate with the authorization server. [...] The authorization server
> MUST support the HTTP Basic authentication scheme for authenticating clients that were issued
> a client password.
> - rfc 6749

Although i see the point raised in the document you pointed to. Maybe it is desirable to turn the HTTP Basic authentication off in certain scenarios. @tkrille, @dacrome do you have an opinion on that?

Please don't restrain yourself from creating issues here! The more the merrier, it enables us to discuss the topics brought up in a focused setting. To answer your question: The access management is wired up in `rest-security.xml` if I'm not mistaken.

**Comment by tkrille** [comment]
@wallner After a brief study of the OAuth spec, it seems to me that we don't support public clients:

> 2.1.  Client Types
> 
>   OAuth defines two client types, based on their ability to authenticate securely with the authorization server (i.e., ability to maintain the confidentiality of their client credentials):
> 
> [...]
> 
>   public
>      Clients incapable of maintaining the confidentiality of their credentials (e.g., clients executing on the device used by the resource owner, such as an installed native application or a web browser-based application), and incapable of secure client authentication via any other means.

and from https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified#other-app-types:

> Browser-based apps run entirely in the browser after loading the source code from a web page. Since the entire source code is available to the browser, they cannot maintain the confidentiality of their client secret, so the secret is not used in this case.

So, OSIAM should be able to flag a client as "public" and based on that, not enforcing (or maybe even denying) HTTP Basic authentication. Let's open a new issue for that.
