### ISSUE TITLE
misleading error if auth and resource server can’t talk to each other

### ISSUE THREAD

**Issue by mirabilos** [osiam/auth-server#55]
org.osiam.client.exception.UnauthorizedException: Your token is not valid

This is what an application gets if OSIAM is misconfigured (wrong scheme/hostname/port in all three *.properties files) and the auth server and resource server can’t talk to each other.

**Comment by wallner** [comment]
Hello @mirabilos,

thank you for opening this issue. It is true that we raise an `UnauthorizedException` the reason for this is that the resource server is unable to validate the presented access token and thus assumes it to be invalid.

We could change that behavior into presenting the user a HTTP error code  503 (Service not available) but i feel that this would leak more information about the interanl architecture of OSIAM then necessary. 

What would be your preferred behavior in the described case that the resource server can't talk to the auth server?

**Comment by mirabilos** [comment]
On Fri, 7 Aug 2015, Florian Wallner wrote:

[ trouble changing the response ]

Hmm, I see.

> What would be your preferred behavior in the described case that the
> resource server can't talk to the auth server?

How about logging something server-side to the log (catalina.out)
in this case, and not changing the error displayed to the consumer?

This way, the admin is empowered to better diagnosis still.

bye,

## //mirabilos

tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by wallner** [comment]
Hello @mirabilos,

thank you for bringing the failure to create a meaningful log message to our attention. That is indeed a bug and should be fixed.

If it is ok for you I would like to create a new issue for this (logging in case of unreachable auth server) in the resource server and close this one.

**Comment by mirabilos** [comment]
This appears to be https://github.com/osiam/resource-server/issues/52 now. I don’t care in which component this is ;-) so, fine with me.

Thanks.
