### ISSUE TITLE
Store tokens in the database

### ISSUE THREAD

**Issue by tkrille** [osiam/auth-server#61]
Currently, access tokens are stored in an in-memory token store provided by Spring Security OAuth. This has some fundamental flaws, for example:
- Restarting the auth-server revokes all access tokens
- The auth-server cannot be scaled on the x-axis of the [scale cube](http://microservices.io/articles/scalecube.html)
- We leak state between the individual integration tests which leads to the unpleasant fact that they are not isolated against each other

Especially the last point has given me a hard time yesterday, when I tried to update the ITs for the removal of the old, method-based scopes.

So, I propose that we put the tokens into the database.

**Comment by dacrome** [comment]
+1. With Spring OAuth it's easy to switch the store for [managing tokens](http://projects.spring.io/spring-security-oauth/docs/oauth2.html#managing-tokens).

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/80
