### ISSUE TITLE
Inactive user, weird error when getting access token

### ISSUE THREAD

**Issue by ohoho7** [osiam/auth-server#62]
When i am trying to get access token with not existing user, I get error which tells me what happen, the  same situation when user is proper but password is incorrect.
Weird behaviour occurs when i am passing proper user credential but for user for which active is not defined on database.
If I set active on true, access token come in standard way. When I set active on false I get:
{"error":"invalid_grant","error_description":"The user with the username 'a1aaaaaaaa' is disabled!"}
which is OK.
But when active is not defined I get html page with:
"There is an internal problem with the client authorization. Please contact your client."
I think that this information is confusing. 
Maybe it will be better to treat not defined active as active=false or not letting creating user without defined this field?
In your documentation I found:

"To create a new user you need to send the user input as JSON via POST to the URL
curl -i -H "Accept: application/json" -H "Content-type: application/json" -H "Authorization: Bearer $YOUR_ACCESS_TOKEN" -X POST http://localhost:8080/osiam-resource-server/Users -d '{"schemas":["urn:scim:schemas:core:2.0:User"],"externalId":"external_id","userName":"arthur","password":"dent"}'"

and this sollution creates user with not defined active field.

**Comment by tkrille** [comment]
Hi @ohoho7,

thanks for your bug report. We are already aware of this issue. See #8. Actually, we thought, that this only happens when you directly create the `User` in the database. #8 states:

> IIRC the resource server will never set the database field to `null`, so that is only a problem when changing the database manually. you're right that the default value is `false`, i.e. inactive. nevertheless we should fix this by simply checking for `null` values.

This seems to be not true. Nevertheless, I'll mark this issue as duplicate and will mention your comments in #8.
