### ISSUE TITLE
Cache client details per request

### ISSUE THREAD

**Issue by tkrille** [osiam/auth-server#67]
I've noticed that 1 request to an OAuth-protected resource on the resource server leads to several roundtrips to the client database. Seems that Spring Security OAuth calls `clientDetailsService.loadClientByClientId(clientId)` for almost every single attribute it has to know about. We should somehow cache the result of `clientDetailsService.loadClientByClientId(clientId)` on a per request basis.

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/81
