### ISSUE TITLE
Make session timeout configurable

### ISSUE THREAD

**Issue by tkrille** [osiam/auth-server#7]
30 minutes is not enough for most of the use cases. Session timeout **MUST** be configurable.

**Comment by dacrome** [comment]
This fruit hangs so low, you just need to grap it from the ground. With Spring Boot it's now configurable with [`server.session-timeout`](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html). The property just need to be documented and added to the [example configuration file](https://github.com/osiam/auth-server/blob/master/src/main/deploy/auth-server.properties).

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/76
