### ISSUE TITLE
Missing logging if authentication/authorization fails

### ISSUE THREAD

**Issue by mley** [osiam/auth-server#75]
Missing logging if redirect_uri from oauth request does not match the client's redirect_uri in the database.

If the redirect uris do not match, the user is shown a vague error message. In the log files, even on debug level, there is no indication why the login failed.

**Comment by mley** [comment]
# Context from ML discussion:

Ich habe die Dateien ueberprueft und einen Fehler gefunden:

Fuer den client "monitor" ist folgende Redirect-URI definert:

```
http://invio-mapserver.lan.tarent.de:8080/monitor/oauth2
```

Wenn du den Authorization-Code-Grant startest, dann schickst du als Redirect-URI allerdings:

```
http://invio-mapserver.lan.tarent.de:8080/monitor/osiam/oauth2
```

Das funktioniert natuerlich nicht, die konfigurierte Redirect-URI MUSS ein Praefix der Redirect-URI sein, die bei der Beantragung eines Authorization-Code benutzt wird. Bitte probiere mal die Konfiguration entsprechend anzupassen.

**Comment by tkrille** [comment]
Accepted as Bug

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/83
