### ISSUE TITLE
Auth Server shall have a URL for Logout

### ISSUE THREAD

**Issue by mley** [osiam/auth-server#83]
We are using OSIAM as IDM for multiple small applications with the OAuth2 authorization flow. The customer wants a logout functionality, so that the user is also logged out from OSIAM.

My suggestion would be: When the user clicks the logout button in our application, he is forwarded to a special logout URL of the auth-server (similar to the redirect URL for login). OSIAM then invalidates the access token issued to this session. A message, that the user has been logged out is displayed and the input fields to log in again. After successful login, the user is again redirected back to the application.

It is important for our use-case, that not all sessions of this user are logged out, since one account may be used by more than one person in parallel. This could be an additional feature (log me out on all browsers/devices), which we don't need at the moment.

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/84
