### ISSUE TITLE
OSIAM {auth,resource}-server 2.3 cannot talk to connector4java 1.4

### ISSUE THREAD

**Issue by mirabilos** [osiam/auth-server#84]
Hi *,

having a minimum requirement of server 2.3 for connector 1.7 is okay, having a minimum required client version for a certain server version is also okay, but if both appear at the same time, the systems need to be upgraded in lockstep, which is not so much okay.

Case in point: VerA.web Online-Anmeldung

ERROR [2015-10-22 17:47:09,502] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 9094fb8c136a34fe
! org.osiam.client.exception.ConflictException: The JSON structure is invalid
! at org.osiam.client.AbstractOsiamService.checkAndHandleResponse(AbstractOsiamService.java:271) ~[vwor.jar:1.6.31.5]

Is it possible? desirable? to have a range of versions that can talk with each other, so that component upgrades need not occur in lockstep (but rather ordered or, even better, arbitrarily)?

**Comment by tkrille** [comment]
Hi @mirabilos,

you're absolutely right with your demands. This particular compatibility issue somehow slipped through our inspections. We will fix this during the next days and release a new version of OSIAM and the connector. The new versions will be 2.5 (core servers 2.4) and 1.8 respectively. You should consider connector 1.7 and the complete OSIAM 2.4 release (core servers 2.3) as broken and not use it.

**Comment by mirabilos** [comment]
On Fri, 23 Oct 2015, Thomas Krille wrote:

> you're absolutely right with your demands. This particular

In this case it was more of a request than demand ;-)

> compatibility issue somehow slipped through our inspections. We will
> fix this during the next days and release a new version of OSIAM and
> the connector. The new versions will be 2.5 (core servers 2.4) and 1.8
> respectively.

OK, thanks.

Wouldn’t it be better if you bumped the core servers version to 2.5 in
the same go, skipping 2.4 altogether, to get them somewhat into sync?

> You should consider connector 1.7 and the complete OSIAM
> 2.4 release (core servers 2.3) as broken and not use it.

OK. We will not ship this then (we did get this combination
working currently, although we had to manually force Jackson
2.5 as Dropwizard included only version 2.3.3 of Jackson).

bye,

## //mirabilos

tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by tkrille** [comment]
> > compatibility issue somehow slipped through our inspections. We will
> > fix this during the next days and release a new version of OSIAM and
> > the connector. The new versions will be 2.5 (core servers 2.4) and 1.8
> > respectively.
> 
> OK, thanks.
> 
> Wouldn’t it be better if you bumped the core servers version to 2.5 in
> the same go, skipping 2.4 altogether, to get them somewhat into sync?

This unfortunate versioning strategy is based on some prior misconceptions what OSIAM should be like. We will fix this with OSIAM 3.0, but not now.

> > You should consider connector 1.7 and the complete OSIAM
> > 2.4 release (core servers 2.3) as broken and not use it.
> 
> OK. We will not ship this then (we did get this combination
> working currently, although we had to manually force Jackson
> 2.5 as Dropwizard included only version 2.3.3 of Jackson).

The issues with Jackson will also be solved with connector 1.8. A fix for this is already on the master branch.

**Comment by tkrille** [comment]
> > Wouldn’t it be better if you bumped the core servers version to 2.5 in
> > the same go, skipping 2.4 altogether, to get them somewhat into sync?
> 
> This unfortunate versioning strategy is based on some prior misconceptions what OSIAM should be >like. We will fix this with OSIAM 3.0, but not now.

We've decided to synchronize the version after all. Next OSIAM release will be 2.5 and auth-server and resource-server will be 2.5, too.

**Comment by tkrille** [comment]
Closed with release 2.5.
