### ISSUE TITLE
Request server version

### ISSUE THREAD

**Issue by mirabilos** [osiam/auth-server#88]
Severity: wishlist

Please add a request that returns the version of the OSIAM auth server that is actually running, including an indication that it’s the OSIAM auth server (to avoid problems like deploying resource server as osiam-auth-server.war caused by a copy/paste mistake). For this reason, please choose a harmonised request path, and make it accessible without auth.

**Comment by mirabilos** [comment]
cf. https://github.com/osiam/resource-server/issues/100
and https://evolvis.org/tracker/t_follow.php/6307

**Comment by dacrome** [comment]
This won't be part of 2.x or respectively the split OSIAM server, but it should be part of the [Monitoring of the OSIAM components](https://github.com/osiam/osiam/issues/8) when the Spring Boot Actuator is used with [custom application information](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info)
